dollar: $
openpos:
  update:
    softwareProvider: fileSystemSoftwareProvider
    installUrl: http://localhost:6142
    installBasePath: ${dollar}{user.dir}
    fileSystemSoftwareProvider:
      artifactExtension: zip
      baseDir: /Users/cshenso/Downloads/artifacts
